config/routes.rb
Rails.application.routes.draw do

  resources :comments, except: %i[index update new edit show] do
    collection do
      post :like
      post :unlike
    end
  end

  resources :feed do
    collection do
      post :follow_unfollow
      get :load_more_button
      get :user_feed_load_more
      post :save_collection
      get :my_friends
      get :mentions
    end
  end

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
        put :update_collection
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: %i[edit update]
    resources :featured_collections, except: %i[edit update]
    resources :edition_drops, except: [:edit, :update] do
      collection do
        post 'add'
      end
    end
    resources :reserve_drops, except: [:edit, :update] do
      collection do
        post 'add'
      end
    end
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    get 'change_network', to: 'dashboard#change_network'
    root to: 'dashboard#index'
  end

  resources :users, except: %i[index create destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      get :following_followers
      post :bid
      post :report
      post :create_contract
      post :moon_pay, path: 'moon-pay'
    end
  end
  resources :collections, only: %i[new show create] do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      get :fetch_swap_details
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_metadata_with_creator
      post :sign_fixed_price
      post :approve
      post :owner_transfer
      post :burn
      post :swap_request
      post :approve_swap
      post :verify_swap
      post :reject_swap
      post :save_contract_nonce_value
      post :get_nonce_value
      post :save_nonce_value
      post :get_contract_sign_nonce
      post :delivery_details
    end
  end

  resources :sessions, only: %i[create destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: %i[create update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  # get 'category', to: 'dashboard#category'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'search/hash-tags/:hash_tag', to: 'dashboard#search_hash_tag', as: 'search_hash_tag'
  get 'edition_drops', to: 'dashboard#edition_drops'
  get 'reserve_drops', to: 'dashboard#reserve_drops'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'
  get 'gas_price', to: 'dashboard#gas_price'
  get 'change_network', to: 'dashboard#change_network'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'airdrop', to: 'static#airdrop'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'
  get 'faq-detail', to: 'static#faq_detail'

  get 'feedstatic', to: 'static#feed'

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:show]
  before_action :is_approved, only: [:show]
  # before_action :set_collection, only: [:show, :bid, :execute_max_bid, :remove_from_sale, :execute_bid, :buy]
  before_action :set_collection, except: [:new, :create, :update_token_id, :sign_metadata_hash]

  skip_before_action :verify_authenticity_token


  def new
    @collection_type = params[:type]
    if params[:nft]
      begin
        asset_response = JSON.parse(URI.open(Rails.application.credentials.config[:opensea_url] + "/api/v1/asset/#{params[:contract_address]}/#{params[:token]}").read)
        if asset_response["top_ownerships"]
          contract_symbol = asset_response["asset_contract"]["symbol"]
          contract_type = (contract_symbol.include?("NFT1155") || contract_symbol.include?("NFT721")) ? "Shared" : "Own"
          num_of_copy = asset_response["top_ownerships"].find { |resp| resp["owner"]["address"].downcase == current_user.address.downcase }.try(:fetch, "quantity")
          data = JSON.parse(URI.open(params[:nft]).read)
          @nft = {
            title: data["name"],
            description: data["description"],
            metadata: params[:nft],
            token: params[:token],
            contract_type: contract_type,
            num_copies: num_of_copy,
            contract_address: params[:contract_address]
          }
          OpenURI::Buffer.send :remove_const, 'StringMax' if OpenURI::Buffer.const_defined?('StringMax')
          OpenURI::Buffer.const_set 'StringMax', 0
          if data.has_key?("image")
            file = URI.open(data["image"])
            @nft.merge!({
              url: data["image"],
              file_path: file.path,
              file_type: file.content_type
            })
          elsif data.has_key?("animation_url")
            file = URI.open("https://ipfs.io/ipfs/" + data["animation_url"].split("://")[1])
            @nft.merge!({
              url: "https://ipfs.io/ipfs/" + data["animation_url"].split("://")[1],
              file_path: file.path,
              file_type: file.content_type,
              preview_url: "https://ipfs.io/ipfs/" + data["image_url"].split("://")[1]
            })
          elsif data.has_key?("image_url")
            file = URI.open("https://ipfs.io/ipfs/" + data["image_url"].split("://")[1])
            @nft.merge!({
              url: "https://ipfs.io/ipfs/" + data["image_url"].split("://")[1],
              file_path: file.path,
              file_type: file.content_type
            })
          end
        else
          raise "Unable to fetch the asset details"
        end
     rescue Exception => e
        Rails.logger.warn "################## Exception while reading Opensea Collection file ##################"
        redirect_to user_path(id: current_user.address, tab: 'nft_collections')
      end
    end
  end

  def show
    @tab = params[:tab]
    @activities = PaperTrail::Version.where(item_type: "Collection", item_id: @collection.id).order("created_at desc")
    @max_bid = @collection.max_bid
    set_collection_gon
  end

  def create
    begin
      # ActiveRecord::Base.transaction do
        @collection = Collection.new(collection_params.except(:source, :nft_link, :token, :total_copies, :contract_address, :contract_type))
        @collection.state = :pending
       if collection_params[:source] == "opensea"
          data = JSON.parse(URI.open(collection_params[:nft_link]).read)
          OpenURI::Buffer.send :remove_const, 'StringMax' if OpenURI::Buffer.const_defined?('StringMax')
          OpenURI::Buffer.const_set 'StringMax', 0
          if data.has_key?("animation_url")
            file = URI.open("https://ipfs.io/ipfs/" + data["animation_url"].split("://")[1])
          elsif data.has_key?("image_url")
            file = URI.open("https://ipfs.io/ipfs/" + data["image_url"].split("://")[1])
          else
            file = URI.open(data["image"])
          end
          @collection.name = data["name"]
          unless @collection.nft_contract.address == collection_params[:contract_address]
            @collection.nft_contract = NftContract.find_or_create_by(contract_type: @collection.nft_contract.contract_type, symbol: collection_params[:contract_type], address: collection_params[:contract_address])
          end
          @collection.royalty = 0
          @collection.token = collection_params[:token]
          @collection.no_of_copies = collection_params[:total_copies]
          @collection.owned_tokens = collection_params[:no_of_copies].present? ? collection_params[:no_of_copies] : collection_params[:total_copies]
          @collection.description = data["description"]
          @collection.attachment.attach(io: file, filename: data["name"], content_type: file.content_type)
          # for music and video if no cover added then we add default banner image as cover
          if ['audio/mp3', 'audio/webm', 'audio/mpeg', 'video/mp4', 'video/webm'].include?(file.content_type) && !@collection.cover.present?
            if data.has_key?("animation_url")
              preview_file = URI.open("https://ipfs.io/ipfs/" + data["image_url"].split("://")[1])
              @collection.cover.attach(io: preview_file, filename: data["name"], content_type: preview_file.content_type)
            else
              @collection.cover.attach(io: File.open('app/assets/images/banner-1.png'), filename: 'banner-1.png')
            end
          end
        else
          @collection.owned_tokens = @collection.no_of_copies
        end
        @collection.network_id = Current.network.id
        # ITS A RAND STRING FOR IDENTIFIYING THE COLLECTION. NOT CONTRACT ADDRESS
        @collection.address = Collection.generate_uniq_token
        @collection.creator_id = current_user.id
        @collection.owner_id = current_user.id
        @collection.data = JSON.parse(collection_params[:data]) if collection_params[:data].present?
        if @collection.valid?
          @collection.save
          @metadata_hash = Api::Pinata.new.upload(@collection)
          # PaperTrail.request(enabled: false) { @collection.approve! }
        else
          @errors = @collection.errors.full_messages
        end
      # end
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def bid
    begin
      if @collection.max_bid.present?
        collection_max_bid = @collection.max_bid.amount
      else
        collection_max_bid = @collection.min_bid_price_val
      end
      bidding_amount = bid_params[:details][:amount]

      if collection_max_bid
        if collection_max_bid < bidding_amount.to_d
          @collection.place_bid(bid_params)
        elsif @collection.max_bid.blank? and (collection_max_bid >= bidding_amount.to_d )
          @collection.place_bid(bid_params)
        else
          raise StandardError.new "Not more than the current maximum bid"
        end
      else
        @collection.place_bid(bid_params)
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating BID ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def swap_request
    begin
      Swap.create!(swap_params)
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating SWAP ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def approve_swap
    begin
      ActiveRecord::Base.transaction do
        @redirect_address = @collection.approve_swap(params[:swap_id], params[:transaction_hash]) if @collection.is_owner?(current_user)
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while swapping collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def verify_swap
    begin
      swap = Swap.find params[:swap_id]
      owner_collection = Collection.where(owner_id: swap.owner_id, id: swap.owner_collection_id).first
      requestor_collection = Collection.where(owner_id: swap.requestor_id, id: swap.requestor_collection_id).first
      if owner_collection.nil? || requestor_collection.nil? || owner_collection.owned_tokens < swap.owner_quantity || requestor_collection.owned_tokens < swap.requestor_quantity
        swap.expire_swap!
        render json: { :success => false, :errors => ["The swap request is expired."] }
      else
        render json: { :success => true }
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while swapping collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def reject_swap
    begin
      swap = Swap.find_by(id: params[:swap_id], owner_collection_id: @collection.id)
      swap.reject_swap!
    rescue Exception => e
      Rails.logger.warn "################## Exception while swapping collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def fetch_swap_details
    swap = Swap.find_by(id: params[:swap_id], owner_collection_id: @collection.id)
    render json: {data: swap.details}
  end

  def remove_from_sale
    if @collection.is_owner?(current_user)
      @collection.remove_from_sale

app/helpers/collections_helper.rb
module CollectionsHelper
  def cover_url(collection)
    return '/assets/dummy-image.jpg' if unauthorized_to_show_attachment(collection)
    attachment = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'].include?(collection.attachment.content_type) ? collection.get_attachment(current_user) : collection.cover
    attachment.present? ? url_for(attachment) : '/assets/banner-1.png'
    # pinata_url(collection)
  end

  def attachment_tag(collection)
    attachment = collection.attachment
    return image_tag '/assets/dummy-image.jpg', class: "img-responsive" if unauthorized_to_show_attachment(collection)

    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      audio_tag url_for(attachment), size: "550x400", controls: true
    elsif ['video/mp4', 'video/webm'].include?(attachment.content_type)
      video_tag url_for(attachment), class: "video-responsive", controls: true
    else
      # image_tag pinata_url(collection), class: "img-responsive"
      image_tag url_for(collection.get_attachment(current_user)), class: "img-responsive"
    end
  end

  def cover_tag(collection)
    attachment = collection.attachment
    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      image_tag cover_url(collection), class: "img-responsive"
    end
  end

  def unauthorized_to_show_attachment(collection)
    # collection.unlock_on_purchase? && (!current_user.present? || (current_user && current_user != collection.owner))
    return false
  end

  def pinata_url(collection)
    collection.image_hash.present? ? "https://gateway.pinata.cloud/ipfs/#{collection.image_hash}" : '/assets/dummy-image.jpg'
  end

  def is_audio_collection?(attachment)
    ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
  end

  def is_video_collection?(attachment)
    ['video/mp4', 'video/webm'].include?(attachment.content_type)
  end

  def explorer
    Rails.application.credentials.explorer
  end

  def explorer
    Rails.application.credentials.send("#{Current.network.short_name}")[:explorer]
  end

  def explorer_transaction(collection)
    url = explorer
    collection&.transaction_hash&.present? ? URI.parse(url +'tx/' + collection&.transaction_hash) : '#' 
  end
end

app/views/collections/_accept_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart acceptBidStart fa fa-check-circle grey"></i>
    <i class="allProgress acceptBidProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone acceptBidDone fa fa-check-circle hide"></i>
    <i class="allRetry acceptBidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <% if @collection.is_lazy_minted? %>
      <h4>Mint and Accept Bid</h4>
      <p class="para-color">Send transaction with your wallet</p>
    <%else%>
      <h4>Accept Bid</h4>
      <p class="para-color">Send transaction with your wallet</p>
    <%end%>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart acceptBidStart disabledLink grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress acceptBidProgress disabledLink hide"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone acceptBidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry acceptBidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_approve_execute_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart approveExecbidStart fa fa-check-circle hide grey"></i>
    <i class="allProgress approveExecbidProgress fa fa-spinner fa-pulse"></i>
    <i class="allDone approveExecbidDone fa fa-check-circle hide"></i>
    <i class="allRetry approveExecbidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('collections.show.approve')%></h4>
    <p class="para-color"><%= t('collections.show.approve_terms')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart approveExecbidStart disabledLink hide grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress approveExecbidProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone approveExecbidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry approveExecbidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_approve_swap_modal.html.erb
<!--Follow steps for swap NFT -- Need to change-->
<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="approveSwapModal">
    <%= hidden_field_tag 'approve_swap_id',  '' %>
    <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"> <%= t('shared.follow_steps') %></h4>
    <div class="signMsg">
      <%= render partial: 'approve_loader_swap' %>
    </div>
  </div>
</div>

app/views/collections/_collection_type.html.erb
<section class="create-collectible-section pt-20 pb-20">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="create-collectible-box">
          <div class="create-collectible-box-header">
            <div class="heading-create-collectible main__title">
              <h2 class="mt-0 mb-0">
                <a href="javascript:history.back()"><img src="/assets/nw_asset/left_arrow.png" class="backarrow" /></a>
                <%= t('collections.form.create_collectible')%>
              </h2>
              
            </div>
          </div>
          <div class="create-collectible-box-body">
            <p class="pt-20"><%= t('collections.form.collection_type_text')%></p>
            <p class="pt-20"><%= t('collections.form.collection_type_txt')%></p>

            <div class="create-collectible-button-box">
              <a class="single-multiple-create" href="<%= new_collection_path(type: "single")%>">
                <%= image_tag "single.png" %>
                <p><%= t('collections.form.single')%></p>
              </a>
              <a class="single-multiple-create" href="<%= new_collection_path(type: "multiple") %>">
                <%= image_tag "multiple.png" %>
                <p><%= t('collections.form.multiple')%></p>
              </a>
            </div>
            <p><%= t('collections.form.collection_privacy')%></p>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/collections/_deploy_contract.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="deployProgress fa fa-spinner fa-pulse"></i>
    <i class="deployDone fa fa-check-circle hide"></i>
    <i class="deployRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h3><%= t('collections.form.deploy_contract')%></h3>
    <p class="para-color"><%= t('collections.form.deploy_contract_msg')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="deployProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="deployDone hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="deployRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_owner.html.erb
<a href="<%= collection_path(collection.address)%>">
  <div class="token-collections">
    <div class="token-collections-images">
      <%= image_tag url_for(collection.owner.profile_image(:icon)), class: 'img-responsive' %>
      <img src="/assets/nw_asset/verified_tick.png" class="verify_img" height="28" />
    </div>
    <div class="token-collections-details">
      <p class="para-color"><%= t('collections.show.owner_token', token: (collection.owned_tokens || 1 ))%></p>
      <h4 data-toggle="tooltip" data-placement="top" title="<%= collection.owner.address %>">
        @<%= collection.owner.masked_address(18, 4) %>
      </h4>
    </div>
  </div>
</a>

app/views/collections/_price_change.html.erb
<div id="change-price" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t('collections.show.change_price') %></h4>
  <%= form_tag(change_price_collection_path, method: :post, remote: true, class: 'change-price-form') do %>
    <%= hidden_field_tag 'id', @collection.address, class: 'nft-detail-name' %>
    <%= hidden_field_tag 'collection_timed_auction_enabled', @collection.timed_auction_enabled? %>

    <div class="modal-body pl-30 pr-30">
      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.put_on_sale') %></label>
          <p class="para-color"><%= t('shared.pos_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <% if @collection.put_on_sale? %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale" checked>
            <% else %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.instant_sale_price') %></label>
          <p class="para-color"><%= t('shared.instant_sale_price_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <input type="checkbox" id="collection_instant_sale_enabled" prevVal="<%= @collection.instant_sale_enabled %>" name="collection[instant_sale_enabled]" <%= 'checked' if @collection.instant_sale_enabled %>>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div id='instPrice' class="row mb-15 <%= 'hide' unless @collection.instant_sale_price.present? %>">
        <div class="col-sm-12">
          <div class="form-group bidBuyInputs bordered">
            <div>
              <input type="text" name="collection[instant_sale_price]" prevVal="<%= @collection.instant_sale_price %>" value="<%= @collection.instant_sale_price %>" class="form-control input-custom sign__input" id="instant-price" placeholder="Enter price for one piece"/>
            </div>
            <div>
              <%= select_tag "collection[erc20_token_id]", options_for_select(Erc20Token.select_options, @collection.erc20_token_id), class: "form-control input-custom sign__input", required: true, prevVal: @collection.erc20_token_id %>
            </div>
          </div>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.unlock_one_purchased') %></label>
          <p class="para-color"><%= t('shared.unlock_one_purchased_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <% if @collection.unlock_on_purchase? %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase" checked>
            <% else %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <div class="row mb-15 unlock-description-section <%= 'hide' unless @collection.unlock_on_purchase? %>">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('collections.show.unlock_description') %></label>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" name="collection[unlock_description]" class="form-control input-custom sign__input" id="collection-unlock-description" placeholder="Enter unlock description" value="<%= @collection.unlock_description %>"/>
          </div>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.direct_nft_delivery') %></label>
          <p class="para-color"><%= t('shared.direct_nft_delivery_one_purchased_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <% if @collection.delivery_on_purchase? %>
              <input type="checkbox" name="collection[delivery_on_purchase]" id="collection-direct-nft-delivery" checked>
            <% else %>
              <input type="checkbox" name="collection[delivery_on_purchase]" id="collection-direct-nft-delivery">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <% if @collection.delivery_on_purchase? and (@collection.delivery_details.present? || @collection.delivery_email.present?) %>
       <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.clear_delivery_details') %></label>
          <p class="para-color"><%= t('shared.clear_delivery_details_for_security_concern') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
              <input type="checkbox" name="collection[clear_delivery_details]" id="collection-clear-delivery-details">
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <% end %>

    </div>
    <div class="modal-footer">
      <%= submit_tag 'Update', class: 'hide', id: 'submitPriceChange', 'data-disable-with': "<i class='fa fa-spinner fa-spin'></i> Updating...".html_safe %>
      <a class="btn bidding-element-btn triggerPriceChange theme-btn" href="javascript:void(0)" role="button">Update</a>
      <a class="bidding-element-btn secondary-btn modal-cancel" data-dismiss="modal" role="button">Cancel</a>
    </div>
  <% end %>
</div>


<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="priceChange">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t('shared.follow_steps') %></h4>
  <div class="modal-body">

    <div class="approveFlow">
      <%= render partial: 'approve' %>
    </div>

    <div class="signFixedPrice hide">
      <%= render partial: 'sign_fixed_price' %>
    </div>
  </div>
</div>

app/views/collections/_success.html.erb
<div className="follow-step-block">
    <div class="follow-step-icon">
      <i class="fa fa-check-circle"></i>
    </div>
    <div class="follow-step-content">
      <h4><%= t('collections.collection')%></h4>
      <p class="para-color"><%= t('collections.successfully_minted')%></p>
    </div>
    <div class="follow-step-button themeBG">
      <a href="<%= my_items_path %>"><%= t('shared.go_to_my_items')%></a>
    </div>
</div>