config/routes.rb
Rails.application.routes.draw do

  resources :comments, except: %i[index update new edit show] do
    collection do
      post :like
      post :unlike
    end
  end

  resources :feed do
    collection do
      post :follow_unfollow
      get :load_more_button
      get :user_feed_load_more
      post :save_collection
      get :my_friends
      get :mentions
    end
  end

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
        put :update_collection
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: %i[edit update]
    resources :featured_collections, except: %i[edit update]
    resources :edition_drops, except: [:edit, :update] do
      collection do
        post 'add'
      end
    end
    resources :reserve_drops, except: [:edit, :update] do
      collection do
        post 'add'
      end
    end
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    get 'change_network', to: 'dashboard#change_network'
    root to: 'dashboard#index'
  end

  resources :users, except: %i[index create destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      get :following_followers
      post :bid
      post :report
      post :create_contract
      post :moon_pay, path: 'moon-pay'
    end
  end
  resources :collections, only: %i[new show create] do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      get :fetch_swap_details
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_metadata_with_creator
      post :sign_fixed_price
      post :approve
      post :owner_transfer
      post :burn
      post :swap_request
      post :approve_swap
      post :verify_swap
      post :reject_swap
      post :save_contract_nonce_value
      post :get_nonce_value
      post :save_nonce_value
      post :get_contract_sign_nonce
      post :delivery_details
    end
  end

  resources :sessions, only: %i[create destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: %i[create update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  # get 'category', to: 'dashboard#category'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'search/hash-tags/:hash_tag', to: 'dashboard#search_hash_tag', as: 'search_hash_tag'
  get 'edition_drops', to: 'dashboard#edition_drops'
  get 'reserve_drops', to: 'dashboard#reserve_drops'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'
  get 'gas_price', to: 'dashboard#gas_price'
  get 'change_network', to: 'dashboard#change_network'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'airdrop', to: 'static#airdrop'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'
  get 'faq-detail', to: 'static#faq_detail'

  get 'feedstatic', to: 'static#feed'

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/edition_drop.rb
class EditionDrop < ApplicationRecord
  belongs_to :collection
  validates_uniqueness_of :collection_id
end

app/controllers/admin/edition_drops_controller.rb
class Admin::EditionDropsController < Admin::BaseController

  def index
    @edition_drops = EditionDrop.joins(:collection).where(collections: {published: true}).paginate(page: params[:page], per_page: 10)
  end

  def new
    per_page=25
    reserve_drops = ReserveDrop.pluck(:collection_id)
    @collections = params[:query].present? ? Collection.search("*#{params[:query].strip}*").records : Collection.all
    @collections = @collections.where(:collection_type=>"single")
    @collections = @collections.where.not(id: reserve_drops).on_instant_sale.by_published.not_timed_auctions.paginate(per_page: per_page, page: params[:page] || 1)
  end

  def add
    col_ids =  params[:edition_drop][:collection_ids].split(',')
    existing_cols = EditionDrop.where(:collection_id=>col_ids).count
    begin
      if col_ids.length > 0 and existing_cols == 0 and params[:edition_drop][:expires_in].present? and params[:edition_drop][:starts_at].present?
        cols =col_ids.map {|ff| {:collection_id => ff, :expires_in => params[:edition_drop][:expires_in] ,
          :created_at=>Time.now,:updated_at=>Time.now, :starts_at => params[:edition_drop][:starts_at]}}
        bulk_insert = EditionDrop.insert_all(cols)
      else
        bulk_insert = nil
      end
    rescue
      bulk_insert = nil
    end
    respond_to do |format|
      format.html { redirect_to :admin_edition_drops, notice:  bulk_insert ?  'Added successfully' : "The action is failed due to presence of duplicate collections or invalid entries." }
      format.json { head :no_content }
    end
  end

  def remove
  end

  def destroy
    edition_drop = EditionDrop.find(params[:id])
    edition_drop.destroy

    respond_to do |format|
      format.html { redirect_to admin_edition_drops_url, notice: "Edition Drop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def edition_drop_params
    params.require(:edition_drop).permit(:collection_ids,:expires_in,:start_at)
  end
end

app/views/admin/edition_drops/index.html.erb
<div class="main-content">
  <div class="page-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6">
                  <h4 style="color:orangered"><%=flash[:notice]%></h4>
                  <h4 class="card-title"><%= t("admin.edition_drops.index.title") %></h4>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                  <%= link_to t("admin.edition_drops.index.add_new"), new_admin_edition_drop_path, class: "float-right btn btn-primary" %>
                </div>
              </div>
              <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                  <tr>
                    <!-- <th><%#= t("admin.edition_drops.index.id") %></th> -->
                    <th><%= t("admin.edition_drops.index.name") %></th>
                    <th><%= t("admin.edition_drops.index.address") %></th>
                    <th><%= t("admin.reserve_drops.index.starts_at") %></th>
                    <th><%= t("admin.reserve_drops.index.expires_in") %></th>
                    <th><%= t("admin.edition_drops.index.category") %></th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% if @edition_drops.present? %>
                    <% @edition_drops.excluding(:reserve_drops).each do |fcollection| %>
                      <tr>
                        <!-- <td><%#= fcollection.id %></td> -->
                        <td><%= fcollection.collection.name %></td>
                        <td><%= fcollection.collection.address %></td>
                        <td><%= fcollection.starts_at %></td>
                        <td><%= fcollection.expires_in %></td>
                        <td><%= fcollection.collection.category.join(',') %></td>
                        <td>
                          <%= link_to "Destroy", admin_edition_drop_path(fcollection), method: :delete, class: "pr-2" %>
                        </td>
                      </tr>
                    <% end %>
                  <% else %>
                    <tr>
                      <td colspan="4" class="text-center"><%= t(:no_records, scope: :admin) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="flickr_pagination">
            <%= will_paginate @edition_drops %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/edition_drops/new.html.erb
<div class="main-content">
  <div class="page-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6">
                  <h4 class="card-title"><%= t("admin.edition_drops.index.title") %></h4>
                </div>
                 <div class="col-sm-6">
                  <%= form_tag(new_admin_edition_drop_path, method: :get, class: '') do %>
                    <div class="row">
                      <div class="col-md-3">
                        <input name="query" type="text" id="name" placeholder="Search:" style="height:34px;" value="<%=params[:query]%>"/>
                      </div>
                      <div class="col-md-3">
                        <button type="submit" class="btn btn-primary btn-no-style">Search</button>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
              <table id="edition-collections" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                  <tr>
                  <th></th>
                  <th>Id</th>
                    <!-- <th><%#= t("admin.edition_drops.index.id") %></th> -->
                    <th><%= t("admin.edition_drops.index.name") %></th>
                    <th><%= t("admin.edition_drops.index.address") %></th>
                                        <th><%= t("admin.edition_drops.index.categories") %></th>


                  </tr>
                </thead>
                <tbody>
                  <% if @collections.present? %>
                    <% @collections.each do |collection| %>
                      <tr>
                        <td></td>
                        <td><%=collection.id%></td>
                        <!-- <td><%#= fcollection.id %></td> -->
                        <td><%= collection.name %></td>
                        <td><%= collection.address %></td>
                                                <td><%= collection.category.join(',') %></td>

                      </tr>
                    <% end %>
                  <% else %>
                    <tr>
                      <td colspan="4" class="text-center"><%= t(:no_records, scope: :admin) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <%= form_tag(add_admin_edition_drops_path, method: :post, id: 'edition_drops_form') do %>

        <div class="card-body">
          <h4 class="card-title"> Other Details</h4>

         <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t("admin.edition.form.start_at") %></label>
            <div class="col-md-10">
                <%= datetime_field_tag 'edition_drop[starts_at]', nil, class: 'form-control' , style: 'width:250px;', placeholder: t('admin.reseve_drops.form.start_at') %>
                <input name="edition_drop[collection_ids]" type="hidden" id="selected_edition_items"/>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t("admin.edition.form.expires_in") %></label>
            <div class="col-md-10">
                <%= datetime_field_tag 'edition_drop[expires_in]', nil, class: 'form-control' , style: 'width:250px;', placeholder: t('admin.reseve_drops.form.expires_in') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"></label>
            <div class="col-md-10">
            <button type="submit" id="edition_add" class="btn btn-primary mr-1 w-md"><%= t('shared.submit')%></button>
            <%= link_to t('shared.cancel'), admin_edition_drops_path, class: "btn btn-secondary w-md add_btn" %>            </div>
          </div>
        </div>
     <% end %>

      <div class="row">
        <div class="col-12">
          <div class="flickr_pagination">
            <%= will_paginate @collections %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

</script>